In [1]:
import numpy as np

In [26]:
myM = np.matrix([[1,2,3], [4,5,6], [7,8,9]])

print(myM)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
myMMean = np.mean(myM, axis=0)
print(myMMean)

[[ 4.  5.  6.]]


In [28]:
print(myM - myMMean)

[[-3. -3. -3.]
 [ 0.  0.  0.]
 [ 3.  3.  3.]]


In [29]:
print(myM.shape[0])


3


In [30]:
myOnes = np.matrix([[1], [1], [1]])
print(myOnes)

[[1]
 [1]
 [1]]


In [31]:
print(myM - (myOnes.dot(myOnes.T).dot(myM)/2))

[[-5.  -5.5 -6. ]
 [-2.  -2.5 -3. ]
 [ 1.   0.5  0. ]]


In [32]:
eig_vals, eig_vecs = np.linalg.eig(myM)
print(eig_vals)
print(eig_vecs)

[  1.61168440e+01  -1.11684397e+00  -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [40]:
print(myM.dot(eig_vecs[:,0]))

[[ -3.73863537]
 [ -8.46653421]
 [-13.19443305]]


In [41]:
print(eig_vecs[:,0]*eig_vals[0])

[[ -3.73863537]
 [ -8.46653421]
 [-13.19443305]]
